### ISSUE TITLE
0.0.8: window content drawing and size issue on startup

### ISSUE THREAD

**Issue by andis-sprinkis** [hismailbulut/neoray#10]
Minor annoyances after launching 0.0.8:
Window content is not of correct size or position, remaining buffer area is filled with the theme background color; unless - part of window is randomly placed outside of the screen, then that remaining buffer area is white.

Resizing window *fixes* it.

![image](https://user-images.githubusercontent.com/52537705/131225584-762daa80-288d-4a05-99e3-fcb757220975.png)

**Comment by hismailbulut** [comment]
I couldn't reproduce the issue. What is your neoray config in your init.vim?

**Comment by andis-sprinkis** [comment]
Only neoray specific logic in config I have is
https://github.com/andis-sprinkis/neovim-user-config/blob/5ed218c5a846b9c77d68e1a4cd3d19c320a1faa8/plugin-pre/app/neoray.vim
loaded in
https://github.com/andis-sprinkis/neovim-user-config/blob/5ed218c5a846b9c77d68e1a4cd3d19c320a1faa8/plugin-pre/app/_init.vim

**Comment by andis-sprinkis** [comment]
I was able to reproduce the same issue with default Neovim settings.
![neoray-win64_e0SEtPbiLk](https://user-images.githubusercontent.com/52537705/131227687-24b5932e-6c50-4b6f-9e69-11a4f7d1bc70.png)

Maybe it has something to do with me using custom display scaling factor:
![ApplicationFrameHost_9WwtBYoH5v](https://user-images.githubusercontent.com/52537705/131227709-f4792c7d-0c71-477e-9294-53609b72ebd6.png)

**Comment by andis-sprinkis** [comment]
Confirmed that the content placement issue is not present when setting back to default display scaling factor.

However, if the window spawns slightly off screen the blank white buffer content issue for that part still is, so that's a separate problem.

![neoray-win64_mhecQzSwkW](https://user-images.githubusercontent.com/52537705/131227840-2215485c-4175-488f-bc86-e319f99efabb.png)
