### ISSUE TITLE
Troubles with dependencies during installation

### ISSUE THREAD

**Issue by bunyk** [hismailbulut/neoray#13]
I just started with fresh Ubuntu 20.04, and decided to try nvim instead of gvim I used to work in. Now looking for GUI for it.

Having Go already installed, I did

```
go install github.com/hismailbulut/neoray/src@latest
```

And got the following fatal errors, one after another fixing them one by one: 

```
X11/Xlib.h: No such file or directory
X11/Xcursor/Xcursor.h: No such file or directory
X11/extensions/Xrandr.h: No such file or directory
X11/extensions/Xinerama.h: No such file or directory
X11/extensions/XInput2.h: No such file or directory
fatal error: GL/glx.h: No such file or directory
Package gtk+-3.0 was not found in the pkg-config search path.
```

These are fixed by 
```
sudo apt install libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev build-essential libgtk-3-dev
```

It would be nice to mention this somewhere in documentation about installation.

Now I'm stuck with
```
# github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lXxf86vm
```

Not sure what that means.

**Comment by bunyk** [comment]
And last one is fixed by

```
sudo apt-get install xorg-dev
```

**Comment by hismailbulut** [comment]
Hello @bunyk and thanks for the pr. I also noticed that neoray_* settings not reloading after resourcing or changing from command line is an another issue and I try the fix it soon.
