### ISSUE TITLE
macOS: Stuck on Loading default font

### ISSUE THREAD

**Issue by andis-sprinkis** [hismailbulut/neoray#18]
**Please complete the following information:**

    Operating System or distro: macOS 10.15.7
    neoray version: 0.0.9

**Describe the bug**
Stuck on 
```
[DEBUG] [NEORAY] Loading default font.
```
and no GUI

**Steps to reproduce**
Start neoray after compilation and with empty init.vim file

**Your neoray config in init.vim**
empty file, but same result with `set guifont=CascadiaCodePL:h10`

**Crash log if available (may be generated by neoray after crash)**

**Debug output (you can generate starting neoray with --verbose option)**
```
$ ./bin/neoray --verbose                                                                                                 22:01:37
[DEBUG] [NVIM] Neovim started with command: nvim --embed
[TRACE] [NVIM] Neovim version 0.5.0
[DEBUG] [NVIM] Attached to neovim as an ui client.
[TRACE] [NEORAY] Glfw version: 3.3.4 Cocoa NSGL EGL OSMesa
[DEBUG] [NEORAY] Video mode {Width:1440 Height:2560 RedBits:8 GreenBits:8 BlueBits:8 RefreshRate:60}
[DEBUG] [NEORAY] Creating window, width: 864 height: 1920
[DEBUG] [NEORAY] Glfw window created successfully.
[DEBUG] [NEORAY] Monitor diagonal: 23.79 dpi: 123.45
[DEBUG] [NEORAY] Input callbacks are initialized.
[DEBUG] [RENDERER] Initializing opengl.
[TRACE] [RENDERER] Opengl Version: 4.1 ATI-3.10.22
[DEBUG] [RENDERER] Vendor: ATI Technologies Inc.
[DEBUG] [RENDERER] Renderer: AMD Radeon Pro 560X OpenGL Engine
[DEBUG] [RENDERER] GLSL: 4.10
[DEBUG] [NEORAY] Loading default font.
```

**Comment by hismailbulut** [comment]
Hello @andis-sprinkis I dont have a macos pc to look and find the issue. As I understand from your previus issue, you are be able to build and run it yourself? Does this issue only happens in prebuilt binaries? Also does it happens every start or sometimes?

**Comment by andis-sprinkis** [comment]
I am unable to test prebuilt binaries on machine I have currently due to permissions, so I have built from release source on the spot. Issue described above happens every time I have tried to launch 0.0.9. Previously tested compilation of 0.0.7 would launch fine.

**Comment by andis-sprinkis** [comment]
Perhaps it's worth trying to use a macOS virtual machine, although virtualized macOS environments normally have very limited graphics capabilities due to limited drivers and not sure if Neoray would work on it for that reason.

**Comment by hismailbulut** [comment]
My pc is a low end device. I cant install a macos virtual machine on this. I will add more debug output to next release and try to figure out where the issue is coming from.

**Comment by andis-sprinkis** [comment]
After checking out virtualization options, I can only confirm that when using typical virtual machine virtualization solution like https://github.com/myspaghetti/macos-virtualbox and previously having set up similar setups on Vmware and Virtualbox, that those won't let Neoray to be run, because the graphics driver compatible with these virtual machines doesn't have GPU acceleration capabilities Neoray requires. So for testing it's either having to use actual Apple machine, or a GPU pass-through VM solution or some service that's lets developer rent a macOS device session.

**Comment by hismailbulut** [comment]
I have tried macos in virtual machine but can't get it working. On linux enabling 3d acceleration in virtualbox settings causes neoray to crash because it doesn't support opengl 3.3 but mesa drivers supports them and they are only loaded when acceleration is off. All libraries and rendering implementation in neoray is macos compatible and needs to run on macos but I don't guarantee that it will be work on virtual machines.

**Comment by hismailbulut** [comment]
Confirmed that this is a neovim related issue. I could be able to open with -u NORC options but have no further information. I will try to understand whats going on.

**Comment by a-gerescher** [comment]
Default font fixed, works as intended. 
Thanks a lot!
