### ISSUE TITLE
Mapping with <bar> or "|" doesn't work

### ISSUE THREAD

**Issue by dcampos** [hismailbulut/neoray#24]
**Please complete the following information:**
 - OS or distro: Linux Mint 
 - neoray version: 0.1.0

**Describe the bug**

Any mapping that contains &lt;bar> (VimScript) or "|" (Lua) doesn't work. I use `<leader>|` to split the current window vertically.

I use a keyboard with Brazilian layout, don't know if that is causing the issue.

**Steps to reproduce**

Just create any mapping with a vertical bar on the left-hand side, as in the examples below.

**Your neoray config in init.vim** (Only the part that concerns neoray!)
```vim
nnoremap <Leader><Bar> <C-W>v

" OR:

lua <<EOF
vim.api.nvim_set_keymap('n', '|', '<c-w>v', { noremap = true })
EOF
```

**Crash log if available (may be generated by neoray after crash)**

**Debug output (you can generate starting neoray with --verbose option)**

**Comment by hismailbulut** [comment]
1- Open an empty file, press <C-v> and press bar key. If it prints something send me it.
2- I looked brazilian layout and bar key is above the windows key, are you pressing Ctrl-Alt or Altgr or alone for typing bar?

**Comment by dcampos** [comment]
1. If I enter insert mode and press `<c-v>|`, it prints `<S-Bar>`. In the terminal (kitty and terminator), it just prints `|`.
2. Yes, it's above the windows key, but behaves just like any other key. To type a vertical bar, I press `Shift+/`

I checked and this issue happens also in neovide: it also prints `<S-Bar>`. It doesn't happen in nvui or neovim-gtk, which are UIs I've used recently.

**Comment by dcampos** [comment]
I've tried the latest release and it works now after the fix. Thanks for looking into this!
