### ISSUE TITLE
Program closes instantly after starting.

### ISSUE THREAD

**Issue by DasOhmoff** [hismailbulut/neoray#3]
Hello. I wanted to try out this gui client. But each time I start the program it just exists automatically without any error messages. Same thing when I execute the program in the cmd prompt. I use windows and tried starting the "neoray_windows_x64.exe" program.

Neovim is in my system path included. But I also tried starting the program it in the neovim directory, doesn't help.

**Comment by hismailbulut** [comment]
Hello @DasOhmoff and thank you for information. Did the program created a crash report after crash? It must be in the same directory you started the neoray. If not, please try starting neoray with "--verbose neoray.log" option. It will generate a file named neoray.log and verboses debug output to it. Please send me these two files if you success. If not, can you compile the program yourself and send me the output?

**Comment by DasOhmoff** [comment]
- The program did not create any crash report.
- Here is the output of the `neoray.log` file after executing the program with the `--verbose` flag:
```
NEORAY v0.0.6 Release LOG 2021-08-14 22:08:41.2770254 +0000 UTC
 [NVIM] TRACE: Neovim started with command: nvim --embed
 [NVIM] TRACE: Neovim version 0.5.0
 [NEORAY] TRACE: Glfw version: 3.3.3 Win32 WGL EGL OSMesa MinGW
 [NEORAY] DEBUG: Monitor diagonal: 25.540107737899678 dpi: 88.65097574877264
```
As you can see it is only 6 lines long, so it is very small.

**Comment by hismailbulut** [comment]
@DasOhmoff sorry for the late response. I have been very busy. I uploaded windows debug build to releases page. Could you try with this one and send me the output?

**Comment by DasOhmoff** [comment]
The output and the log are still the same. Output: 
![image](https://user-images.githubusercontent.com/16063186/129848535-e80a26fb-3c2f-44b5-b564-3b797d4b92ff.png)

Log:
```

NEORAY v0.0.6 Debug LOG 2021-08-18 07:27:29.6636714 +0000 UTC
 [NVIM] TRACE: Neovim started with command: nvim --embed
 [NVIM] TRACE: Neovim version 0.5.0
 [NEORAY] TRACE: Glfw version: 3.3.3 Win32 WGL EGL OSMesa MinGW
 [NEORAY] DEBUG: Monitor diagonal: 25.540107737899678 dpi: 88.65097574877264

```

**Comment by hismailbulut** [comment]
Aleykümselam brother @DasOhmoff. Yes, I am muslim elhamdülillah. I could not be able to find your problem for now because program does not give any information. And I decided to increase count of debugging information. For now I will ask you to wait and try future versions. I keep this issue open and let me know if there are any progress.

**Comment by DasOhmoff** [comment]
Will do so my brother <3 . Wa alaikum assalam warahmatullahi wabarakatuh!

**Comment by hismailbulut** [comment]
Hey @DasOhmoff the last release has to fix this issue. Please try and let me know if it was fixed.

**Comment by DasOhmoff** [comment]
Yes! It got fixed. Thank you very much.

**Comment by hismailbulut** [comment]
You are welcome @DasOhmoff and thanks for your support. Try different names like Ubuntu_Mono. We can also discuss it if you open a new issue.
