### ISSUE TITLE
Neoray cannot load the font.

### ISSUE THREAD

**Issue by ishan9299** [hismailbulut/Neoray#30]
**Please complete the following information:**
 - OS or distro: Windows 11
 - neoray version: 0.1.1
 
**Describe the bug**
neoray cannot find the font 'Iosevka Slab:h16'. This is the same guifont I use in neovim-qt and fvim.

**Steps to reproduce**

**Your neoray config in init.vim** (Only the part that concerns neoray!)
```vim

```

**Crash log if available (may be generated by neoray after crash)**

**Debug output (you can generate starting neoray with --verbose option)**

**Comment by hismailbulut** [comment]
Try file name of the font. For example you have 4 files with names:
```
Losevka_Regular.ttf
Losevka_Bold.ttf
Losevka_Italic.ttf
Losevka_BoldItalic.ttf
```

In this situationt setting guifont to Losevka will be fine.
```
set guifont=Losevka:h16
```

Let me know if this not help you.

**Comment by ishan9299** [comment]
I installed a different variant of Iosevka font because I wasn't sure if previous one was ttf or not. I installed "Iosevka Term Curly Slab". In the control panel fonts section (where you can see all the installed fonts in windows) the Font name is "Iosevka Term Curly Slab". When type the command `set guifont=Iosevka\ Term\ Curly\ Slab:h10` it shows the error font not found.

**Comment by ishan9299** [comment]
Ok found it. It works I'd suggest you give the path `C:\Users\%USERNAME%\AppData\Local\Microsoft\Windows\Fonts` in Readme to check the font name. Now I know for some reason windows has 2 different names for same font 🤮.
