### ISSUE TITLE
chinaese can not display

### ISSUE THREAD

**Issue by guolimin1995** [hismailbulut/Neoray#32]
**Please complete the following information:**
 - OS or distro: macos 10.15.4
 - neoray version: 0.1.1

**Describe the bug**
can not display chinaese

**init.vim**
  if exists('g:neoray')
	  set guifont=Ubuntu\ Mono:h13
      NeoraySet CursorAnimTime 0.05
      NeoraySet Transparency   1
      NeoraySet TargetTPS      60
      NeoraySet ContextMenuOn  TRUE
      NeoraySet BoxDrawingOn   TRUE
  endif

**Comment by guolimin1995** [comment]
![QQ20220324-101223](https://user-images.githubusercontent.com/29330637/159828270-bcd5cc24-b9a9-44fc-837b-07831777931a.png)

**Comment by guolimin1995** [comment]
> ![image](https://user-images.githubusercontent.com/73897211/159996749-e660d37c-de1d-4e48-89a5-fa74b15c2977.png) I don't know anything about Chinese but I was able to display a Chinese text using NotoSansSC font. But there is still a problem with the spacing of the characters. Since I'm very busy these days, I took a break from development, but I can check this soon.

thanks for check. maybe is my font problem or character issue.

**Comment by paopaol** [comment]
the same problem. but  nvim-qt works fine.my font is  `Fira Code`

**Comment by paopaol** [comment]
but i was used neovide too, it also works fine

**Comment by hismailbulut** [comment]
It seems like neovide's default font has Chinese characters. I can't pack default font with Chinese because it's increases the binary size a lot. Currently I am working on a new renderer and I can look into this after it's done.
