### ISSUE TITLE
Detach from terminal?

### ISSUE THREAD

**Issue by dR3b** [hismailbulut/Neoray#34]
Hi! Great project!

I often use "neoray" in the terminal (alacritty), which is blocked after startup:
```bash
» neoray
[TRACE] [NVIM] Neovim version 0.7.0
[TRACE] [NEORAY] Glfw version: 3.3.4 X11 GLX EGL OSMesa clock_gettime evdev
[TRACE] [RENDERER] Opengl Version: 4.6 (Core Profile) Mesa 22.1.2
[TRACE] [PERFORMANCE] Start time: 141.210204ms
[ERROR] [NEORAY] Assertion Failed: print() function used in release build
Grid.Resize, ID: 1 Rows: 33 Cols: 88
[TRACE] [NEORAY] Regular: UbuntuMono-R.ttf
[TRACE] [NEORAY] Bold Italic: UbuntuMono-BI.ttf
[TRACE] [NEORAY] Italic: UbuntuMono-RI.ttf
[TRACE] [NEORAY] Bold: UbuntuMono-B.ttf
[ERROR] [NEORAY] Assertion Failed: print() function used in release build
Grid.Resize, ID: 1 Rows: 40 Cols: 114
[ERROR] [NEORAY] Assertion Failed: print() function used in release build
Grid.Resize, ID: 1 Rows: 94 Cols: 81
```
Is it possible to prevent this?

Currently I use a "wrapper" (`gvim`):
```bash
#!/usr/bin/env bash
neoray "$@" > /dev/null 2>&1 &
disown %1
```

**Comment by hismailbulut** [comment]
> Hi! Great project!

Thank you, I am working hard to make it great and I appreciate you for being part of this

Actually I don't know anything about bash and I didn't understand the issue, so I will ask you some questions.
1- What do you mean by "blocked", is it crashed or stuck somewhere?
2- Does this happen older versions of Neoray?
3- Does this happen when starting Neoray normally, without any script?
4- What your bashscript does

And also currently I am rewriting and organizing most of the codebase, I can only look into this after I finish my current tasks.

**Comment by dR3b** [comment]
I have made two screenshots:

Neoray:
![20220628-071842](https://user-images.githubusercontent.com/9670938/176098937-7beaee2f-9fd0-453a-891f-be0b001d73b3.png)

My wrapper script:
![20220628-071940](https://user-images.githubusercontent.com/9670938/176098986-cab96c67-7647-4fe7-86f9-9b0352d1f4f3.png)

I can work with my workaround but I think this would be a good improvement.

**Comment by hismailbulut** [comment]
I didn't read the title, sorry :)

So this is something like feature request. Currently in windows Neoray already detaches from terminal. But on linux and macos we need additional detach. This may be default procedure or we can add a new option for it. Either way I can't do this myself because I don't want to install a linux or macos emulator. I would be happy to accept a pr here.

**Comment by dR3b** [comment]
I'm excited for a new release 🥲
