### ISSUE TITLE
[Ctrl + an unmapped key] combination crashes neoray

### ISSUE THREAD

**Issue by andis-sprinkis** [hismailbulut/neoray#4]
Resulting in error message "Invalid scancode"

![error screenshot](https://i.imgur.com/n89Zq9u.png)

neoray-win64.exe 'latest' release c421526

**Comment by andis-sprinkis** [comment]
Update: sorry, it wasn't Caps Lock, but keycode + for a disabled key (00_00).
I pressed Ctrl + Win where Win is an unmapped key in Windows Registry.
![keys](https://i.imgur.com/yn5VXM3.png)

**Comment by hismailbulut** [comment]
Hey @andis-sprinkis the last release has to fix this issue. Please try and let me know if it was fixed.

**Comment by andis-sprinkis** [comment]
Seems to be fixed on 0.0.7 neoray-win64, not experiencing the issue on this version.

**Comment by hismailbulut** [comment]
Thanks for your support @andis-sprinkis. Please reopen this issue if you encounter again.
