### ISSUE TITLE
Resolution Problem On macOS

### ISSUE THREAD

**Issue by Corgile** [hismailbulut/Neoray#41]
## OS or distro:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/48396880/201743425-848e5f1f-bbfe-4c43-b052-48b2dfa119d1.png">

### 1. right after startup

<img width="800" alt="image" src="https://user-images.githubusercontent.com/48396880/201743854-bbb220d7-1b0c-4334-9f0e-dcef77f5f79a.png">

### 2. press any key

<img width="800" alt="image" src="https://user-images.githubusercontent.com/48396880/201743938-0252df27-4f16-4198-8642-8b2f4d362b1e.png">

### everything works fine but the resolution is malfunctioning on macOS 13 Ventura.
please fix this, thank you

**Comment by hismailbulut** [comment]
Thanks for reporting. Is the second image correct? In my understanding the problem only happens at startup and fixed after a key press. And I need to ask your vim configuration (only include Neoray related part)

**Comment by corgile** [comment]
> Is the second image correct?


## sorry for confusing, here is full screen capture of the second picture

**after pressing some key or mouse clicking, the text size goes very big, and `:set guifont=JetBrains\ Mono:h16` takes no effect (font exists), also the viewing area doesn't fill up the window**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48396880/202601819-a8f14fbe-8cf7-4c45-bf85-54a17094538b.png">

## and there are no special Neoray configs currently

<img width="771" alt="image" src="https://user-images.githubusercontent.com/48396880/202600976-c3aadff0-d4e9-4ee6-a80e-a81543913ca7.png">


ps: actually I don't know how to write configurations on Neoray in lua LOL

**Comment by hismailbulut** [comment]
What happens when you start Neoray with `-u NORC --noplugin` options? And for the font write the filename of the font. It may be JetBrainsMono without space.

**Comment by hismailbulut** [comment]
> I have a fix for this issue here: [annacrombie@393d29b](https://github.com/annacrombie/Neoray/commit/393d29bb47f5c93cf13c268661f55baa7849037f). I'm not sure if its worth making a PR though.

I will be happy to review it if you make a pr
