### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by hosseinkhojany** [hismailbulut/Neoray#42]
it possible to use `sudo` command to run tun 
currently neoray using osascript
my program will be signed with developer id certifcate
      `p.start("osascript", {"-e", QString("do shell script \"%1\" with administrator privileges")
                                        .arg("pkill -2 -U 0 nekobox_core")});`

**Comment by hismailbulut** [comment]
I don't know anything about osascript or applescript. Sorry about that. If they require some sort of support from applications it probably not work. If it is similar to sh it should work.
