### ISSUE TITLE
Neoray does not work with nvim 0.9.2+

### ISSUE THREAD

**Issue by annacrombie** [hismailbulut/Neoray#44]
[nvim 0.9.2](https://github.com/neovim/neovim/releases/tag/v0.9.2) lists as a breaking change:

> An adjustment was made to the grid_line event as part of the external UI protocol:
> the cells array might now end with a [' ', attr, 0] item with a repeat count of
> zero. This is needed by the TUI to disambiguate final spaces from a line from just
> clearing the line, which will make a difference when copying text using the terminal
> emulators' builtin primary selection support.
> 
> External UIs can safely ignore such an empty item and most UIs already handle this fine.
> But it could break UIs which has an assert to validate the cell count to be bigger
> than zero, or similar.

I tried adding code similar to 468a3f30d8782708acb654c7b350d3ad609c293f, but noticed artifacts, for instance create a vertical split and then add new lines to the right-hand split, and I observed the separator to start getting chars overwritten with empty space.

**Comment by hismailbulut** [comment]
Thanks for the report. Let me know if the b357fe4 fixes the issue.
