### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Dominiquini** [hismailbulut/Neoray#45]
**Please complete the following information:**
 - OS or distro: Windows 10 x64
 - neoray version: 0.2.5

**Describe the bug**
The application crashs on startup

**Steps to reproduce**
Just click on the application .exe

**Your neoray config in init.vim** (Only the part that concerns neoray!)
```vim

```

**Crash log if available (may be generated by neoray after crash)**
[Neoray_crash.log](https://github.com/hismailbulut/Neoray/files/13162243/Neoray_crash.log)

**Debug output (you can generate starting neoray with --verbose option)**
[Neoray_verbose.log](https://github.com/hismailbulut/Neoray/files/13162248/Neoray_verbose.log)

Thanks

**Comment by hismailbulut** [comment]
It is already fixed in the master but latest release is broken. You can build it from yourself or wait for next release.
