### ISSUE TITLE
Feature request: CSI u modifiers

### ISSUE THREAD

**Issue by andis-sprinkis** [hismailbulut/neoray#5]
In [suckless st](https://st.suckless.org/) and [iterm2](https://iterm2.com/index.html) terminal emulators I can use Ctrl+Alt+H / J / K / L as mappings in Neovim. I use these mappings to resize Neovim panes when running it in these terminal emulators.
```vim
" resize splits
nnoremap <silent><C-A-j> :resize +2<cr>
nnoremap <silent><C-A-k> :resize -2<cr>
nnoremap <silent><C-A-l> :vertical resize +4<cr>
nnoremap <silent><C-A-h> :vertical resize -4<cr>
```

In iterm2 these kind of shortcuts work after enabling this feature: https://iterm2.com/documentation-csiu.html
It seems like something that currently is not available in Neovim Qt or in neoray.

Could support for these mappings be added to neoray?

**Comment by hismailbulut** [comment]
You are be able to use this keybindings from now on. Please try latest release and send me your feedback.

**Comment by andis-sprinkis** [comment]
My Ctrl-Alt-* mappings work without issue now. Thanks! This along with great performance makes neoray one of the better Neovim clients :)

**Comment by hismailbulut** [comment]
Thank you. I hope it will be. Input mappings is very important for me and that's actually why I started writing this program. Always report if there are any input issues.
