### ISSUE TITLE
Cannot load custom font.

### ISSUE THREAD

**Issue by DasOhmoff** [hismailbulut/neoray#8]
Hello :wave: :)
Thank you for your support!

I tried using different fonts using neoray, but that does not seem to be working.

Here is the font that I have installed:
![image](https://user-images.githubusercontent.com/16063186/131092520-dfa3ed7f-acef-4592-b757-e8c4346ff5a1.png)

Here is my .vimrc config line:
```
set guifont=UbuntuMono_NF:h8
```

And here is neorays output on startup:
![image](https://user-images.githubusercontent.com/16063186/131092695-d2736293-3c06-499d-abec-06c2946bf5cf.png)

If I use the same configuration on some other gui client, then it seems to work correctly.

**Comment by DasOhmoff** [comment]
Hello, I have not tested your suggestion yet, I did not come to it until now, have a lot of stuff to do. I will inform you when I test it :)

**Comment by hismailbulut** [comment]
Sorry

**Comment by DasOhmoff** [comment]
> I know this is not like you used to. But finding a font from it's family name is not an easy thing and it changes os to os.
It's all cool brother, don't worry <3 :)

> If it can't find with family name you need to write a name from file name.
Ah yes! That is it. Now it seems to work, setting the fonts file name resolves the issue!

Sorry for keeping this open for so long, it seems this was easier to fix than I expected.

**Comment by hismailbulut** [comment]
I uploaded new version and started the close some issues, and thinked that you may fixed your issue and forgot to write here and closed this one also. I am glad you success!

**Comment by DasOhmoff** [comment]
:)
