### ISSUE TITLE
Slightly transparent application window issue

### ISSUE THREAD

**Issue by andis-sprinkis** [hismailbulut/neoray#9]
neoray-win64.exe 0.0.7

Custom window transparency level is *not* set, nor external application is used to change window transparency.

Normal screenshot:
![normal screenshot](https://i.imgur.com/eF1YYsN.png)

Screenshot enhanced in image editor to see that windows in background are visible through it:
![enhanced screenshot](https://i.imgur.com/ADSTlwU.png)

**Comment by andis-sprinkis** [comment]
In example I am using `gruvbox8_hard`, but it is also noticeable on built in dark themes like `darkblue`.

**Comment by hismailbulut** [comment]
Sorry but I dont understand what is the issue. It seems like second photo is more bright.

**Comment by andis-sprinkis** [comment]
It may require quite color sensitive monitor to notice, but it can be noticed that neoray window is slightly (1-3%) transparent.
Another example.

Original screenshot:
[original screenshot](https://i.imgur.com/Qran0JL.png)

Screenshot with contrast and brightness levels adjusted to see:
[visually enhanced screenshot](https://i.imgur.com/uhHplK8.png)

**Comment by hismailbulut** [comment]
Ok I see. It is difficult to see but I am very happy that you see this issue. I divided every color by 256 when it should be 255 :) It also affects all colors and now fixed. Thanks.

**Comment by hismailbulut** [comment]
This issue should not happen in the latest release. Please try and let me know.

**Comment by andis-sprinkis** [comment]
Not experiencing this issue on 0.0.9
